"""Serving layer (FastAPI) for the Site Selection Engine.

Decoupled from PostGIS: serves from versioned artifacts generated by the pipeline
(parquet rankings, .joblib models, GeoJSON POIs). PostGIS is only used in the local
ETL. See docs/despliegue.md.
"""
