"""MODEL v4 — Look-alike classifier with DEMOGRAPHICS (DANE census + IDECA stratum).

Same model (Logistic Regression) and same HONEST validation as v3 (spatial CV with
res-6 H3 blocks + buffer). The only thing that changes is the predictor set: v4 adds
the demographic features (`poblacion_estimada`, `viviendas_estimadas`, `estrato_promedio`)
that didn't exist in v3 (census not loaded).

Question v4 answers, honestly: **does demographics improve the ranking?**
To isolate its contribution, TWO models are evaluated with an identical spatial CV
scheme:
  - BASE  : predictors without demographics  (== v3's predictors)
  - FULL  : BASE + demographics               (== v4)
and their OOF metrics are compared. If demographics doesn't move the needle, that's
reported as-is (same as v3's honest finding about spatial leakage being smaller than
expected).

NULL handling: city blocks don't cover the whole grid -> demographics has partial
NULLs. `build_model()` (in lookalike.py) includes a `SimpleImputer(median)` fit inside
each fold; no hexagons are dropped.

Run (requires data/processed/features.parquet with demographics loaded):
    uv run python -m src.models.lookalike_v4
"""

from __future__ import annotations

import joblib
import numpy as np
import pandas as pd

from src import config
from src.logging_config import get_logger
from src.models.lookalike import (
    build_model,
    coefficients_table,
    load_features,
    select_predictors,
)
from src.models.lookalike_v3 import evaluate_scores, spatial_cv_oof
from src.models.metrics import ranking_report

logger = get_logger(__name__)


# --------------------------------------------------------------------------- #
# Predictor split: base (no demographics) vs full (with demographics)
# --------------------------------------------------------------------------- #
def split_predictors(df: pd.DataFrame) -> tuple[list[str], list[str], list[str]]:
    """Returns (full_predictors, base_predictors, demographics_present).

    `full_predictors` = all usable non-leakage predictors (includes any demographic
    feature that has some data). `base_predictors` excludes the demographic features
    (replicates v3's set). `demographics_present` are the ones that actually made it in.
    """
    full = select_predictors(df)  # already excludes leakage and 100%-null columns
    demo_present = [c for c in config.DEMOGRAPHIC_COLS if c in full]
    base = [c for c in full if c not in config.DEMOGRAPHIC_COLS]
    return full, base, demo_present


def _precision_at_k_oof(df: pd.DataFrame, proba_oof: np.ndarray, k: int) -> float:
    """Honest Precision@K over the OOF predictions."""
    return float(
        df.assign(_p=proba_oof).sort_values("_p", ascending=False)
        .head(k)[config.LABEL_COL].mean()
    )


# --------------------------------------------------------------------------- #
# Summary
# --------------------------------------------------------------------------- #
def write_summary(
    df: pd.DataFrame,
    base_pred: list[str],
    full_pred: list[str],
    demo_present: list[str],
    base_oof: dict,
    full_oof: dict,
    base_prec: float,
    full_prec: float,
    coefs: pd.DataFrame,
) -> None:
    k = config.TOP_K
    cm = full_oof["confusion_matrix"]

    def _delta(a: float, b: float) -> str:
        d = b - a
        return f"{'+' if d >= 0 else ''}{d:.4f}"

    comp_rows = [
        ("ROC-AUC (OOF)", base_oof["roc_auc"], full_oof["roc_auc"]),
        ("PR-AUC (OOF)", base_oof["pr_auc"], full_oof["pr_auc"]),
        (f"NDCG@{k}", base_oof["ranking"]["ndcg_at_k"], full_oof["ranking"]["ndcg_at_k"]),
        (f"Precision@{k}", base_prec, full_prec),
        (f"top-{k} hitting", base_oof["ranking"]["topk_hitting"], full_oof["ranking"]["topk_hitting"]),
    ]

    # Demographic coverage (city blocks don't cover the whole grid).
    cov_rows = [
        f"| `{c}` | {df[c].notna().mean() * 100:.1f}% | {df[c].isna().mean() * 100:.1f}% |"
        for c in demo_present
    ]

    lines = [
        "# Results v4 — Look-alike with demographics (DANE census + IDECA stratum)\n",
        f"_Generated by `src/models/lookalike_v4.py`. Total hexagons: **{len(df)}**._\n",
        "## What changes from v3\n",
        "**Same model** (Logistic Regression) and **same validation** (spatial CV with "
        "res-6 H3 blocks + 1-ring buffer). The only new thing: **demographic** features "
        "prorated by city block are added — population and households (DANE census "
        "CNPV 2018) and socioeconomic stratum (IDECA Bogota).\n",
    ]
    if not demo_present:
        lines += [
            "> **NOTICE:** no demographic features with data were detected in "
            "`features.parquet` (census/stratum not loaded). v4 degenerates to v3. Load "
            "the layers (`src/data/load_censo.py`, `src/data/load_estrato.py`), recompute "
            "the features and rerun v4 for a real comparison.\n",
        ]
    else:
        lines += [
            f"Demographic features that made it into the model: `{'`, `'.join(demo_present)}`.\n",
            "**Coverage** (hexagons without a residential city block are NULL and get "
            "imputed with the median inside each fold):\n",
            "| Feature | % with data | % NULL (imputed) |",
            "|---|---|---|",
            *cov_rows,
            "",
        ]

    lines += [
        "## Contribution of demographics — BASE (no demo, = v3) vs FULL (with demo, = v4)\n",
        "Both are evaluated with the **identical** spatial CV scheme (OOF predictions). "
        "This way the delta isolates the contribution of demographics, not of the "
        "validation method.\n",
        f"- BASE  ({len(base_pred)} preds): `{'`, `'.join(base_pred)}`",
        f"- FULL  ({len(full_pred)} preds): `{'`, `'.join(full_pred)}`\n",
        "| Metric | BASE (v3) | FULL (v4) | Δ (v4 - v3) |",
        "|---|---|---|---|",
        *[f"| {nm} | {a:.4f} | {b:.4f} | {_delta(a, b)} |" for nm, a, b in comp_rows],
        "",
        _verdict_text(base_oof, full_oof, demo_present),
        "\n## Honest v4 diagnostics (OOF predictions)\n",
        f"- **ROC-AUC**: {full_oof['roc_auc']:.4f} | **PR-AUC**: {full_oof['pr_auc']:.4f}",
        f"- **NDCG@{k}**: {full_oof['ranking']['ndcg_at_k']:.4f} | "
        f"**Precision@{k}**: {full_prec:.4f} | "
        f"**top-{k} hitting**: {full_oof['ranking']['topk_hitting']:.4f}\n",
        "**OOF confusion matrix** (threshold 0.5; rows = actual, columns = predicted):\n",
        "| | pred 0 | pred 1 |",
        "|---|---|---|",
        f"| **actual 0** | {cm[0, 0]} | {cm[0, 1]} |",
        f"| **actual 1** | {cm[1, 0]} | {cm[1, 1]} |",
        "\n**Per-class report (OOF):**\n",
        "```",
        full_oof["classification_report"].rstrip(),
        "```\n",
        "## Interpretability — final model coefficients (full-data)\n",
        "Over standardized features (comparable). Sign = direction of the effect on "
        "`P(D1-type)`; magnitude = relative importance. The production ranking uses the "
        "full-data model; the metrics above come from the OOF predictions.\n",
        coefs.round(4).to_markdown(index=False),
        _estrato_reading(coefs, demo_present),
        "\n## Limitation\n",
        "It's still a **similarity / exploration priority** score (not "
        "performance), with the look-alike assumption that D1's siting is good "
        "(docs/metodologia.md §5). Demographics adds market context, it doesn't turn "
        "the score into a sales prediction.\n",
    ]
    config.LOOKALIKE_V4_SUMMARY_PATH.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Summary written -> %s", config.LOOKALIKE_V4_SUMMARY_PATH.name)


def _verdict_text(base_oof: dict, full_oof: dict, demo_present: list[str]) -> str:
    if not demo_present:
        return (
            "> **Verdict:** with no demographics loaded, v4 == v3 (nothing to compare)."
        )
    d_ndcg = full_oof["ranking"]["ndcg_at_k"] - base_oof["ranking"]["ndcg_at_k"]
    d_auc = full_oof["roc_auc"] - base_oof["roc_auc"]
    if d_ndcg > 0.01 or d_auc > 0.01:
        return (
            "> **Verdict:** demographics **improves** performance "
            f"(Δ NDCG@K {d_ndcg:+.4f}, Δ ROC-AUC {d_auc:+.4f}). It contributes market "
            "signal (population size and stratum) that the OSM features didn't capture. "
            "v4 becomes the production model."
        )
    if d_ndcg < -0.01 or d_auc < -0.01:
        return (
            "> **Verdict:** demographics **worsens** OOF performance "
            f"(Δ NDCG@K {d_ndcg:+.4f}, Δ ROC-AUC {d_auc:+.4f}). Possible noise/redundancy "
            "or insufficient demographic coverage. v3 is kept as production and the "
            "result is documented (honest, the improvement is not forced)."
        )
    return (
        "> **Verdict:** demographics **doesn't materially move** the metrics "
        f"(Δ NDCG@K {d_ndcg:+.4f}, Δ ROC-AUC {d_auc:+.4f}). Honest finding: the "
        "competition/complementary/road-network signal already captured almost all of "
        "the linear information; demographics adds interpretability (e.g. the stratum "
        "coefficient) more than predictive power. Production decision made on "
        "parsimony/interpretability grounds."
    )


def _estrato_reading(coefs: pd.DataFrame, demo_present: list[str]) -> str:
    if "estrato_promedio" not in demo_present:
        return ""
    row = coefs.loc[coefs["feature"] == "estrato_promedio"]
    if row.empty:
        return ""
    coef = float(row["coef"].iloc[0])
    sign = "negative" if coef < 0 else "positive"
    consistent = "**consistent**" if coef < 0 else "**contrary to expectations**"
    return (
        f"\n> **Reading of stratum:** `estrato_promedio` coefficient = {coef:.4f} "
        f"({sign} relationship with P(D1-type)). This is {consistent} with the "
        "business hypothesis (D1 is a hard-discount chain focused on lower strata: the "
        "lower the stratum, the more likely D1's presence)."
    )


# --------------------------------------------------------------------------- #
# Orchestration
# --------------------------------------------------------------------------- #
def main() -> None:
    config.DATA_PROCESSED.mkdir(parents=True, exist_ok=True)

    df = load_features()
    full_pred, base_pred, demo_present = split_predictors(df)
    y = df[config.LABEL_COL].astype(int)

    if not demo_present:
        logger.warning("No demographic features with data: v4 degenerates to v3. "
                       "Load census/stratum and recompute features for a real comparison.")

    logger.info("Spatial CV: parent res=%d, folds=%d, buffer=%d ring(s)",
                config.SPATIAL_CV_BLOCK_RES, config.SPATIAL_CV_FOLDS,
                config.SPATIAL_CV_BUFFER_RINGS)

    # OOF with demographics (FULL = v4).
    proba_full, _ = spatial_cv_oof(df, full_pred)
    full_oof = evaluate_scores(y.to_numpy(), proba_full, k=config.TOP_K)
    full_prec = _precision_at_k_oof(df, proba_full, config.TOP_K)
    logger.info("FULL (v4) OOF -> ROC-AUC=%.4f | NDCG@%d=%.4f",
                full_oof["roc_auc"], config.TOP_K, full_oof["ranking"]["ndcg_at_k"])

    # OOF without demographics (BASE = v3) to isolate the contribution.
    if base_pred and base_pred != full_pred:
        proba_base, _ = spatial_cv_oof(df, base_pred)
    else:
        proba_base = proba_full  # no demographics: base == full
    base_oof = evaluate_scores(y.to_numpy(), proba_base, k=config.TOP_K)
    base_prec = _precision_at_k_oof(df, proba_base, config.TOP_K)
    logger.info("BASE (v3) OOF -> ROC-AUC=%.4f | NDCG@%d=%.4f",
                base_oof["roc_auc"], config.TOP_K, base_oof["ranking"]["ndcg_at_k"])

    # Final full-data model for the production ranking (with demographics).
    final_model = build_model()
    final_model.fit(df[full_pred], y)
    score_prod = final_model.predict_proba(df[full_pred])[:, 1]
    coefs = coefficients_table(final_model, full_pred)

    ranking = df[["h3_index", "lat_centroid", "lon_centroid", config.LABEL_COL]].copy()
    ranking["score_lookalike_v4"] = score_prod   # production (full-data model)
    ranking["score_oof"] = proba_full            # honest (transparency)
    ranking["rank_lookalike_v4"] = (
        ranking["score_lookalike_v4"].rank(ascending=False, method="first").astype(int)
    )
    ranking = ranking.sort_values("rank_lookalike_v4").reset_index(drop=True)

    ranking.to_parquet(config.LOOKALIKE_V4_RANKING_PARQUET_PATH, index=False)
    ranking.to_csv(config.LOOKALIKE_V4_RANKING_CSV_PATH, index=False)
    joblib.dump(final_model, config.LOOKALIKE_V4_MODEL_PATH)
    logger.info("Ranking -> %s (+ .csv) | model -> %s",
                config.LOOKALIKE_V4_RANKING_PARQUET_PATH.name,
                config.LOOKALIKE_V4_MODEL_PATH.name)

    write_summary(df, base_pred, full_pred, demo_present,
                  base_oof, full_oof, base_prec, full_prec, coefs)
    logger.info("v4 (demographics) complete.")


if __name__ == "__main__":
    main()
